name: dotprompt
description: >-
  Dart implementation of Dotprompt, an executable prompt template file format
  for Generative AI. This library provides parsing, rendering, and management of
  .prompt files with YAML frontmatter and Handlebars templating.
version: 0.0.2
license: Apache-2.0
homepage: https://github.com/google/dotprompt
repository: https://github.com/google/dotprompt
documentation: https://google.github.io/dotprompt/
environment:
  sdk: ^3.5.0
dependencies:
  collection: ^1.18.0
  crypto: ^3.0.6
  handlebars_dart: ^0.0.1
  json_schema: ^5.2.2
  meta: ^1.15.0
  path: ^1.9.0
  yaml: ^3.1.2
dependency_overrides:
  handlebars_dart:
    path: ../handlebars_dart
dev_dependencies:
  build_runner: ^2.4.13
  coverage: ^1.11.0
  lints: ^5.1.1
  mockito: ^5.4.4
  test: ^1.25.8
